///
/// @Generated by Mockolo
///



import CoreGraphics
import Foundation
@testable import Kase3DEngine
import MetalKit


class CameraMock: Camera {
    init() { }
    init(projectionMatrix: float4x4, viewMatrix: float4x4) {
        self._projectionMatrix = projectionMatrix
        self._viewMatrix = viewMatrix
    }



    private var _projectionMatrix: float4x4!
    var projectionMatrix: float4x4 {
        get { return _projectionMatrix }
        set { _projectionMatrix = newValue }
    }


    private var _viewMatrix: float4x4!
    var viewMatrix: float4x4 {
        get { return _viewMatrix }
        set { _viewMatrix = newValue }
    }

    private(set) var updateCallCount = 0
    var updateHandler: ((CGSize) -> ())?
    func update(size: CGSize) {
        updateCallCount += 1
        if let updateHandler = updateHandler {
            updateHandler(size)
        }
        
    }

    private(set) var updateDeltaTimeCallCount = 0
    var updateDeltaTimeHandler: ((Float, InputProviding) -> ())?
    func update(deltaTime: Float, inputProviding: InputProviding) {
        updateDeltaTimeCallCount += 1
        if let updateDeltaTimeHandler = updateDeltaTimeHandler {
            updateDeltaTimeHandler(deltaTime, inputProviding)
        }
        
    }
}

class MeshLoadingMock: MeshLoading {
    init() { }
    init(device: any MTLDevice) {
        self._device = device
    }



    private var _device: (any MTLDevice)!
    var device: any MTLDevice {
        get { return _device }
        set { _device = newValue }
    }

    private(set) var loadMeshesCallCount = 0
    var loadMeshesHandler: ((URL, TextureLoading) throws -> [Mesh])?
    func loadMeshes(from assetURL: URL, textureLoader: TextureLoading) throws -> [Mesh] {
        loadMeshesCallCount += 1
        if let loadMeshesHandler = loadMeshesHandler {
            return try loadMeshesHandler(assetURL, textureLoader)
        }
        return [Mesh]()
    }
}

class RenderContextMock: RenderContext {
    init() { }
    init(device: MTLDevice, commandQueue: MTLCommandQueue, library: MTLLibrary) {
        self._device = device
        self._commandQueue = commandQueue
        self._library = library
    }



    private var _device: MTLDevice!
    var device: MTLDevice {
        get { return _device }
        set { _device = newValue }
    }


    private var _commandQueue: MTLCommandQueue!
    var commandQueue: MTLCommandQueue {
        get { return _commandQueue }
        set { _commandQueue = newValue }
    }


    private var _library: MTLLibrary!
    var library: MTLLibrary {
        get { return _library }
        set { _library = newValue }
    }
}

class SceneRenderingMock: SceneRendering {
    init() { }


    private(set) var drawCallCount = 0
    var drawHandler: ((ModelScene, MTKView) -> ())?
    func draw(scene: ModelScene, in view: MTKView) {
        drawCallCount += 1
        if let drawHandler = drawHandler {
            drawHandler(scene, view)
        }
        
    }
}

class TextureLoadingMock: TextureLoading {
    init() { }
    init(device: any MTLDevice) {
        self._device = device
    }



    private var _device: (any MTLDevice)!
    var device: any MTLDevice {
        get { return _device }
        set { _device = newValue }
    }

    private(set) var loadTextureCallCount = 0
    var loadTextureHandler: ((MDLTexture, String) -> MTLTexture?)?
    func loadTexture(texture: MDLTexture, name: String) -> MTLTexture? {
        loadTextureCallCount += 1
        if let loadTextureHandler = loadTextureHandler {
            return loadTextureHandler(texture, name)
        }
        return nil
    }

    private(set) var loadTextureNameCallCount = 0
    var loadTextureNameHandler: ((String) -> MTLTexture?)?
    func loadTexture(name: String) -> MTLTexture? {
        loadTextureNameCallCount += 1
        if let loadTextureNameHandler = loadTextureNameHandler {
            return loadTextureNameHandler(name)
        }
        return nil
    }

    private(set) var clearCacheCallCount = 0
    var clearCacheHandler: (() -> ())?
    func clearCache() {
        clearCacheCallCount += 1
        if let clearCacheHandler = clearCacheHandler {
            clearCacheHandler()
        }
        
    }
}

class InputProvidingMock: InputProviding {
    init() { }
    init(mouseDelta: float2, mousePan: float2, magnification: CGFloat = 0.0) {
        self._mouseDelta = mouseDelta
        self._mousePan = mousePan
        self.magnification = magnification
    }


    private(set) var mouseDeltaSetCallCount = 0
    private var _mouseDelta: float2! { didSet { mouseDeltaSetCallCount += 1 } }
    var mouseDelta: float2 {
        get { return _mouseDelta }
        set { _mouseDelta = newValue }
    }

    private(set) var mousePanSetCallCount = 0
    private var _mousePan: float2! { didSet { mousePanSetCallCount += 1 } }
    var mousePan: float2 {
        get { return _mousePan }
        set { _mousePan = newValue }
    }

    private(set) var magnificationSetCallCount = 0
    var magnification: CGFloat = 0.0 { didSet { magnificationSetCallCount += 1 } }
}

class TransformableMock: Transformable {
    init() { }
    init(transform: Transform) {
        self._transform = transform
    }


    private(set) var transformSetCallCount = 0
    private var _transform: Transform! { didSet { transformSetCallCount += 1 } }
    var transform: Transform {
        get { return _transform }
        set { _transform = newValue }
    }
}



